name: Build and Test

on: [push]

jobs:
    Build:
      runs-on: ubuntu-latest
      env: 
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_NAME: sgd-api
        API_PORT: 333
      
      steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build MySQL image
        run: |
          docker build . --file Dockerfile.mysql \
            --build-arg MYSQL_ROOT_PASSWORD=${{ env.DB_PASSWORD }} \
            --build-arg MYSQL_DATABASE=${{ env.DB_NAME }} \
            --tag my-mysql-image

      - name: Start MySQL server container
        run: |
          docker run -d \
            -e MYSQL_ROOT_PASSWORD=${{ env.DB_PASSWORD }} \
            -e MYSQL_DATABASE=${{ env.DB_NAME }} \
            -p ${{ env.DB_PORT }}:3306 \
            my-mysql-image

      - name: Build API image
        run: |
          docker build . --file Dockerfile \
            --build-arg API_PORT=${{ env.API_PORT }} \
            --tag my-api-image

      - name: Start API server container
        run: |
          docker run -d \
            -p ${{ env.API_PORT }}:${{ env.API_PORT }} \
            my-api-image

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0' 

      # - name: Install Python dependencies
      #   run: |
      #     pip install -r requirements.txt 

      - name: Run Python tests
        run: |
          python tests/test_clients.py
