name: Build and Test

on: [push]

jobs:
    Build:
      runs-on: ubuntu-latest
      env: 
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_NAME: sgd-api
      
      steps:
      - name: Check out repository
        uses: actions/checkout@v2
  
      - name: Build MySQL image
        run: |
          docker build . --file Dockerfile.mysql \
            --build-arg MYSQL_ROOT_PASSWORD=${{ env.DB_PASSWORD }} \
            --build-arg MYSQL_DATABASE=${{ env.DB_NAME }} \
            --tag my-mysql-image
  
      - name: Start MySQL server container
        run: |
          docker run -d \
            -e MYSQL_ROOT_PASSWORD=${{ env.DB_PASSWORD }} \
            -e MYSQL_DATABASE=${{ env.DB_NAME }} \
            -p ${{ env.DB_PORT }}:3306 \
            my-mysql-image
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0'  # Ou a versão que você está usando
      
      - name: Test main.go
        run: |
          go run main.go
